import { app, BrowserWindow } from 'electron';
import { LoggedInAccount } from './ipctypes';
import { MyDynamicsWebApi } from './auth/dynamicswebapiconnection';
import { FetchXmlResponse } from 'dynamics-web-api';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}
const dynamicsApi = new MyDynamicsWebApi();

const createWindow = async (): Promise<void> => {
  const loginPromise = dynamicsApi.executeFetchXml('systemusers', `<fetch>
      <entity name="systemuser">
        <attribute name="fullname" />
        <attribute name="systemuserid" />
        <attribute name="internalemailaddress" />
        <filter>
          <condition attribute="systemuserid" operator="eq-userid" />
        </filter>
      </entity>
    </fetch>`
  )
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  await loginPromise.then((result: FetchXmlResponse<{internalemailaddress: string; fullname: string;}>) => {
    console.log(result);
    mainWindow.webContents.send('authenticated', {
      email: result.value[0].internalemailaddress,
      name: result.value[0].fullname
    } as LoggedInAccount)
  }, (err) => {
    console.log('Error during login:');
    console.log(err);
    app.quit();
  });

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.


(async () => {
  await app.whenReady();
// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
  createWindow()

})()
