import * as path from 'node:path';
import { app, BrowserWindow, globalShortcut, ipcMain, Menu } from 'electron';
import { LoggedInAccount } from './ipctypes';
import { MyDynamicsWebApi } from './auth/dynamicswebapiconnection';
import { UserService } from './services/userservice';
import { ProjectService } from './services/projectservice';
import { RecordedDataService, RecordedTimeEntry } from './services/recordeddataservice';
import { TimeEntryService } from './services/timeentryservice';
import { ProcessedDayEntry } from './dayentryprocessing';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}
Menu.setApplicationMenu(null);
const recordedDataService = new RecordedDataService(app.getPath('userData'));

// Populated once the async bootstrap below completes, before app.whenReady() resolves and
// before createWindow() can be called (either from the bootstrap itself or from 'activate').
let userService: UserService;
let projectService: ProjectService;
let timeEntryService: TimeEntryService;

// Tracked so the global "activate window" shortcut can reach it regardless of which function
// created the window (initial launch vs 'activate').
let activeWindow: BrowserWindow | null = null;

const createWindow = async (): Promise<void> => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    // Only used in dev - a packaged build gets its icon from packagerConfig.icon instead. The
    // path reaches out of the webpack output (.webpack/main) to the repo-root assets folder,
    // since this file isn't bundled by webpack's asset pipeline.
    icon: path.join(__dirname, '../../assets/icon.ico'),
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });
  activeWindow = mainWindow;
  mainWindow.on('closed', () => {
    if (activeWindow === mainWindow) {
      activeWindow = null;
    }
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  await userService.getLoggedInUser().then((result: LoggedInAccount) => {
    mainWindow.webContents.send('authenticated', result);
  }, (err) => {
    console.log('Error during login:');
    console.log(err);
    app.quit();
  });
};

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

app.on('will-quit', () => {
  globalShortcut.unregisterAll();
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.


(async () => {
  const dynamicsApi = await MyDynamicsWebApi.create(app.getPath('userData'));
  userService = new UserService(dynamicsApi);
  projectService = new ProjectService(dynamicsApi);
  timeEntryService = new TimeEntryService(dynamicsApi, userService);

  await app.whenReady();
  ipcMain.handle('get-logged-in-user', () => userService.getLoggedInUser() )
  ipcMain.handle('get-all-projects', () => projectService.getAllProjects() )
  ipcMain.handle('get-tasks-for-project', (_, msdyn_projectid: string) => projectService.getTasksForProject(msdyn_projectid) )
  ipcMain.handle('get-all-recorded-data', () => recordedDataService.getAll() )
  ipcMain.handle('save-recorded-data', (_, date: string, entries: RecordedTimeEntry[]) => recordedDataService.save(date, entries) )
  ipcMain.handle('get-uploaded-days', () => recordedDataService.getUploadedDays() )
  ipcMain.handle('upload-day-entries', async (_, date: string, entries: ProcessedDayEntry[]) => {
    await timeEntryService.uploadDayEntries(date, entries);
    await recordedDataService.markDayUploaded(date);
  })

  const shortcutRegistered = globalShortcut.register('Super+Ctrl+T', () => {
    if (!activeWindow) {
      return;
    }
    if (activeWindow.isMinimized()) {
      activeWindow.restore();
    }
    activeWindow.show();
    activeWindow.focus();
  });
  if (!shortcutRegistered) {
    console.log('Could not register the Super+Ctrl+T global shortcut - it may already be in use by another application.');
  }

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
  createWindow()

})()
